import { useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import data from '../../../data/news-data';
import Error from '../../_error';
import Navbar from '../../../components/Navbar';
import Footer from '../../../components/Footer';
import BasketModal from '../../../components/Modals/BasketModal';
import SubscribeModal from '../../../components/Modals/SubscribeModal';
import styles from '../../../styles/blog.module.css';

export default function SingleBlog() {
	const router = useRouter()
  	const { slug } = router.query

	const success = data.find(item => 
		item.id == slug
	);

	// SUBSCRIBE AND BASKET MODAL
	const [subscribeModal, setSubscribeModal] = useState(false);
	const [basketModal, setBasketModal] = useState(false);
	const subscribe = async(ev) => {
		ev.preventDefault();
		setSubscribeModal(!subscribeModal);
	}
	const basket = async(ev) => {
		ev.preventDefault();
		setBasketModal(!basketModal);
	}

	return (
		<div>
			<Head>
				<title>ЧЕКМАРКЕТ</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
				<link rel="manifest" href="/site.webmanifest"/>
				<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
				<meta name="msapplication-TileColor" content="#da532c"/>
				<meta name="theme-color" content="#ffffff"/>
			</Head>

			{ slug !== undefined ?
				success ? 
					<div>
						{ basketModal ? <BasketModal close={ basket }/> : null };
						{ subscribeModal ? <SubscribeModal modal={ subscribe }/> : null };
								
						<Navbar modal={ basket }/>

						<div className={ styles.logo_container }>
							<div className={ styles.logo_box }>
									<img src='/home/logo.svg' alt='logo' className={ styles.logo } />
							</div>
						</div>
								
						<div className={ styles.container }>
							<div className={ styles.header }>
								<h3 className={ styles.title }>Блог</h3>

								<div className={ styles.icons }>
									<Image src='/modal/rectangle.svg' alt='rectangle' width={ 15 } height={ 15 } layout='fixed' />
									<Image src='/modal/triangle.svg' alt='triangle' width={ 40 } height={ 15 } layout='fixed' />
									<Image src='/modal/ellipse.svg' alt='ellipse' width={ 15 } height={ 15 } layout='fixed' />
								</div>

								<p className={ styles.subtitle }>Читайте полезные статьи и последние новости от ЧЕК МАРКЕТ</p>
							</div>

							<div className={ styles.box }>
								<div className={ styles.title_content }>
									<Link href='/blog'>
										<Image src='/blog-icons/arrow2.svg' alt='back arrow' width={40} height={10} layout='fixed' />
										<p>Вернуться</p>
									</Link>

									<div className={  styles.title_content_header }>
										<h6 style={ (window.innerWidth > 992) ? { display: 'none' } : { display: 'block' } }>{ success.date }</h6>
										<h6>Статьи</h6>
									</div>
									
									<h3 className={ styles.title }>{ success.title }</h3>
								</div>
										
								<div className={ styles.image_content }>
									<Image src={ success.image } alt='blog image' width='100%' height='100%' layout='fill' />
									<div className={ styles.frame }></div>
																		
									<div className={ styles.date }>
										<h4>{ success.date }</h4>
									</div>
								</div>
							</div>
							
							<div className={ styles.text_content }>
								<h6>Статьи</h6>
								<p className={ styles.text }>{ success.text1 }</p>
								<p className={ styles.text }>{ success.text2 }</p>
							</div>
						</div>

						<Footer modal={ subscribe }/>
					</div>
						:
					<Error/>
					:
				<></>
			}
		</div>
	);
}
