import Head from 'next/head';
import Button from '../components/Button';
import styles from '../styles/error.module.css';
import styled from 'styled-components';

export default function NotFound() {
   return (
        <div>
            <Head>
					<title>ЧЕКМАРКЕТ</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
					<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
					<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
					<link rel="manifest" href="/site.webmanifest"/>
					<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
					<meta name="msapplication-TileColor" content="#da532c"/>
					<meta name="theme-color" content="#ffffff"/>
				</Head>
			
				<div className={styles.container}>
					<h1 className={styles.title}>404</h1>
					<h3 className={styles.subtitle}>Страница не найдена</h3>
					<p className={styles.text}>Запрашиваемая страница не найдена, возможно она была удалена</p>
					<a href='/'>
						<ButtonContainer>
							<Button text={ "Вернуться на главную" }/>
						</ButtonContainer>
					</a>
				</div>
        </div>
    );
}

const ButtonContainer = styled.div`
	width: 27.5rem;
	height: 4.375rem;
	margin: auto;

	@media (max-width: 1440px) {
		.text {
			font-size: 20px;
		}
	}

	@media (max-width: 1220px) {
		width: 22.5rem;
		height: 3.75rem;

		.text {
			font-size: 18px;
		}
	}
	
	@media (max-width: 992px) {
		width: 20rem;
		height: 3.125rem;

		.text {
			font-size: 15px;
		}
	}
	
	@media (max-width: 650px) {
		width: 13.125rem;
		height: 2.5rem;

		.text {
			font-size: 13px;
		}
	}
`