import Head from 'next/head';
import Button from '../components/Button';
import styles from '../styles/error.module.css';

export default function NotFound() {
   return (
        <div>
            <Head>
					<title>ЧЕКМАРКЕТ</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
					<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
					<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
					<link rel="manifest" href="/site.webmanifest"/>
					<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
					<meta name="msapplication-TileColor" content="#da532c"/>
					<meta name="theme-color" content="#ffffff"/>
				</Head>
			
				<div className={styles.container}>
					<h1 className={styles.title}>404</h1>
					<h3 className={styles.subtitle}>Страница не найдена</h3>
					<p className={styles.text}>Запрашиваемая страница не найдена, возможно она была удалена</p>
					<a href='/'>
						<div className={styles.section_button}>
							<Button text={" Вернуться на главную "}/>
						</div>
					</a>
				</div>
        </div>
    );
}