import { useState, useContext, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styled from 'styled-components';
import { Context } from '../context/Context';
import Error from './_error';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Button from '../components/Button';
import ProductItem from '../components/ModalProductItem';
import BasketModal from '../components/Modals/BasketModal';
import SubscribeModal from '../components/Modals/SubscribeModal';
import bg2 from '../public/home/background.png';

export default function Basket() {
	const { state } = useContext(Context);
	const cart = state.cart;

	const [total, setTotal] = useState();

	function price(numb) {
		if (!numb) 
		return numb;
		
		const numbFmt = new Intl.NumberFormat('ru-RU').format(numb);
		return numbFmt;
	}
	
	useEffect(() => {
		const totalArray = cart.map(item =>
			(item.quantity * item.product.price *  (100 - item.product.sale) / 100)
		)
		setTotal(totalArray.reduce((acc, curr) => acc + Number(curr), 0))
	}, [cart]);

	// SUBSCRIBE AND BASKET MODAL
	const [subscribeModal, setSubscribeModal] = useState(false);
	const [basketModal, setBasketModal] = useState(false);
	const subscribe = async(ev) => {
		ev.preventDefault();
		setSubscribeModal(!subscribeModal);
	}
	const basket = async(ev) => {
		ev.preventDefault();
		setBasketModal(!basketModal);
	}
	
	return (
		<div>
			<Head>
				<title>ЧЕКМАРКЕТ</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
				<link rel="manifest" href="/site.webmanifest"/>
				<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
				<meta name="msapplication-TileColor" content="#da532c"/>
				<meta name="theme-color" content="#ffffff"/>
			</Head>

			{ (window.innerWidth > 650) ? 
				<Error/>
					:
				<>
					{ basketModal ? <BasketModal close={ basket }/> : null };
					{ subscribeModal ? <SubscribeModal modal={ subscribe }/> : null };

					<Navbar modal={ basket }/>
					
					<LogoContainer>
						<div className='logo-box'>
							<img src='/home/logo.svg' alt='logo' className='logo' />
						</div>
					</LogoContainer>

					<Wrapper>
						<div className='container'>
							<div className='header'>
								<h3 className='title'>Корзина</h3>

								<div className='icons'>
									<Image src='/modal/rectangle.svg' alt='rectangle' width={ 10 } height={ 10 } layout='fixed' />
									<Image src='/modal/triangle.svg' alt='triangle' width={ 28 } height={ 10 } layout='fixed' />
									<Image src='/modal/ellipse.svg' alt='ellipse' width={ 10 } height={ 10 } layout='fixed' />
								</div>
							</div>

							{ (cart.length) ?
								<div>
									<div className='content'>
										{ cart.map((item, idx) =>
											<ProductItem product={ item.product } quantity={ item.quantity } key={ idx } />
										) }
									</div>

									<div className='footer'>
										{ (total < 10000) ?
											<p className='requirements'>Минимальная сумма заказа 10000 тг.</p>
												:
											<></>
										}

										<div className='basket-payment'>
											<p className='basket-text'>К оплате:</p>
											<h3>{ price(total) } тг.</h3>
										</div>

										{ (total > 10000) ? 
											<Link href='/order'>
												<div className='basket-button'>
													<Button text={ 'Оформить заказ' }/>
												</div>
											</Link>
												:
											<div className='basket-button'>
												<Button text={ 'Оформить заказ' }/>
											</div>
										}
									</div>
								</div>
									:
								<div className='center'>
									<Image src='/basket/empty.svg' alt='empty basket' width={ 200 } height={ 190 } layout='fixed' />
									<h3 className='title'>Ваша корзина пуста</h3>
									<div className='basket-text'>Выберите необходимые товары, чтобы пополнить её</div>
									<Link href='/shop/catalog/1'>
										<div className='basket-button'>
											<Button text={ 'Начать покупки' }/>
										</div>
									</Link>
								</div>
							}
						</div>
					</Wrapper>

					<Footer modal={ subscribe }/>
				</>
			}
		</div>
	);
}

const LogoContainer = styled.div`
	height: 15.625rem;
	display: grid;
	justify-content: center;
	background-image: url(${bg2.src});
	background-size: cover;
	margin-top: 1.875rem;
	padding-top: 2.5rem;

	@keyframes animate {
		50%, 60%, 70%, 100% {
			opacity: 100%;
		} 0%, 55%, 65% {
			opacity: 0;
		}
	}
	
	@keyframes logoAnimation {
		0% {
			top: 0;
			opacity: 0;
		} 5% {
			opacity: 1;
		} 50% {
			top: 100%;
		} 95% {
			opacity: 1;
		} 100% {
			top: 0;
			opacity: 0;
		}
	}

	.logo-box {
		position: relative;
		width: 8.75rem;
		height: 8.125rem;
	}

	.logo {
		width: 8.75rem;
		height: 8.125rem;
		animation: animate 1.2s linear;
	}

	.logo-box:before {
		content: '';
		position: absolute;
		width: 100%;
		height: 0.3rem;
		background-color: var(--clr-primary-1);
		opacity: 0;
		animation: logoAnimation 2s linear;
	}
	
	.logo-box:active {
		animation: animate 1.2s linear;
	}

	@media (max-width: 480px) {
		height: 11.875rem;
		background-image: url(${bg2.src});
		background-repeat: no-repeat;
		background-size: cover;

		.logo-box {
			position: relative;
			width: 7.5rem;
			height: 6.875rem;
		}
	
		.logo {
			width: 7.5rem;
			height: 6.875rem;
			animation: animate 1.2s linear;
		}
	}
`

const Wrapper = styled.section`
	display: grid;
	justify-content: center;

	.container {
		position: relative;
		margin: auto;
		margin: 1.875rem 0 5.625rem;
	}

	.header {
		margin-bottom: 1.875rem;
	}
	
	.title {
		line-height: 2.0625rem;
		font-size: 22px;
	}
	
	.icons {
		height: 0.9375rem;
	}

	.content {
		position: relative;
		padding-bottom: 0.625rem;
	}

	.content:before {
		content: '';
		position: absolute;
		width: 100%;
		height: 1px;
		bottom: 0;
		background-color: var(--clr-primary-4);
	}

	.footer {
		position: relative;
		margin-top: 1.25rem
	}

	.basket-payment {
		display: flex;
		align-items: center;
		gap: 0.625rem;
	}

	.requirements {
		color: var(--clr-primary-1);
		margin-bottom: 0.625rem
	}

	.basket-text,
	.basket-payment h3,
	.requirements {
		line-height: 1.25rem;
		font-size: 18px;
	}
	
	.basket-button {
		height: 2.5rem;
		margin-top: 1.25rem
	}
	
	.center {
		width: 88.889vw;
		text-align: center;
	}
	
	.center .title {
		font-size: 16px;
		color: var(--clr-primary-1);
		margin: 1.25rem 0 0.625rem;
	}
	
	.center .basket-text {
		font-size: 15px;
		margin-bottom: 1.25rem;
	}
	
	.center .basket-button {
		width: 13.125rem;
		margin: auto;
	}

	.center .text {
		line-height: 1.25rem;
		font-size: 13px;
	}

	@media (max-width: 480px) {
		.title {
			line-height: 1.875rem;
			font-size: 18px;
		}
		
		.icons {
			height: 0.625rem;
		}
	}
`
