import { useState } from 'react';
import Head from 'next/head';
import SubscribeModal from '../components/SubscribeModal';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
// import styles from '../styles/home.module.css';

export default function Home() {
  const [subscribeModal, setSubscribeModal] = useState(false);
	
	const subscribe = async(ev) => {
		ev.preventDefault();
		setSubscribeModal(!subscribeModal);
	}

  return (
    <div>
      <Head>
        <title>ЧЕКМАРКЕТ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c"/>
        <meta name="theme-color" content="#ffffff"/>
      </Head>

      {subscribeModal ?
				<SubscribeModal modal={ subscribe }/>
					:
				<>
					<Navbar home={ true }/>
					<h1>Главная</h1>
					<Footer modal={ subscribe }/>
				</>
			}
    </div>
  );
}